export const KAFKA_CONSTANT = {
  KAFKA_BROKER_1: 'KAFKA_BROKER_1',
  KAFKA_BROKER_2: 'KAFKA_BROKER_2',
  KAFKA_TOPIC_PRODUCER: 'KAFKA-TOPIC-CREATION',
  KAFKA_PARTITION: 3,
  KAFKA_REPLICATION: 1,
  KAFKA_CLIENT_ID: 'KAFKA-CLIENT-ID',
};
